name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/upload-artifact@v3
        with:
          name: publish
          path: |
            ${{ github.workspace }}/manifest.json
            ${{ github.workspace }}/config.js
            ${{ github.workspace }}/scripts
            ${{ github.workspace }}/images/icons/icon128.png
